### ISSUE TITLE
addInboundMessageListener is not trigerred when sending/receiving a message

### ISSUE THREAD

**Issue by mkassir95** [sco0ter/babbler#176]
addInboundMessageListener is not trigerred when sending/receiving a message

this is my logs of ejabberd

> ejabberd  | 2022-12-27 11:54:51.739128+00:00 [info] (<0.744.0>) Accepted connection [::ffff:172.20.0.1]:45692 -> [::ffff:172.20.0.2]:5347
ejabberd  | 2022-12-27 11:54:51.855040+00:00 [info] (tcp|<0.744.0>) Accepted external component handshake authentication for mymuc.domain.tld from ::ffff:172.20.0.1
ejabberd  | 2022-12-27 11:55:03.927789+00:00 [info] API call send_message [{<<"type">>,<<"chat">>},
ejabberd  |                        {<<"from">>,<<"admin@localhost">>},
ejabberd  |                        {<<"to">>,<<"mohammad@localhost">>},
ejabberd  |                        {<<"subject">>,<<"message">>},
ejabberd  |                        {<<"body">>,<<"bardo ba3do meshe l">>}] from ::ffff:172.20.0.1:55104

**Comment by mkassir95** [comment]
This my main java class

> package org.xmpp.docs.simplemuc;

import rocks.xmpp.addr.Jid;
import rocks.xmpp.core.XmppException;
import rocks.xmpp.core.session.XmppSessionConfiguration;
import rocks.xmpp.core.session.debug.ConsoleDebugger;
import rocks.xmpp.core.stanza.model.Message;
import rocks.xmpp.core.stanza.model.Presence;
import rocks.xmpp.core.stanza.model.StanzaError;
import rocks.xmpp.core.stanza.model.errors.Condition;
import rocks.xmpp.extensions.caps.EntityCapabilitiesManager;
import rocks.xmpp.extensions.component.accept.ExternalComponent;
import rocks.xmpp.extensions.disco.ServiceDiscoveryManager;
import rocks.xmpp.extensions.disco.model.info.Identity;
import rocks.xmpp.extensions.muc.model.Affiliation;
import rocks.xmpp.extensions.muc.model.Muc;
import rocks.xmpp.extensions.muc.model.Role;
import rocks.xmpp.extensions.muc.model.user.MucUser;
import rocks.xmpp.extensions.muc.model.user.Status;
import rocks.xmpp.im.subscription.PresenceManager;

import java.util.HashMap;

public class Main {

    private static final HashMap<Jid, RoomState> ROOMS = new HashMap<>();

    public static void main(String... args) {
        final XmppSessionConfiguration.Builder builder = XmppSessionConfiguration.builder();

        if (Configuration.isDebug()) {
            builder.debugger(ConsoleDebugger.class);
        }

        ExternalComponent externalComponent = ExternalComponent.create(
                Configuration.getComponentName(),
                Configuration.getSharedSecret(),
                Configuration.getHostname(),
                Configuration.getPort());

        externalComponent.addInboundMessageListener(messageEvent -> {
        	System.out.println("message received");
            final Message message = messageEvent.getMessage();
            if (message.getTo().isDomainJid()) {
                if (message.getType() == Message.Type.ERROR) {
                    return;
                }
                externalComponent.sendMessage(message.createError(Condition.SERVICE_UNAVAILABLE));
            }

            if (message.getType() == Message.Type.GROUPCHAT && message.getTo().isBareJid()) {
                final Jid roomJid = message.getTo().asBareJid();
                final RoomState roomState = ROOMS.get(roomJid);
                if (roomState == null) {
                    final Message error = message.createError(new StanzaError(StanzaError.Type.CANCEL, Condition.ITEM_NOT_FOUND, "group chat does not exists"));
                    externalComponent.sendMessage(error);
                    return;
                }
                Participant sender;
                try {
                    sender = roomState.getParticipant(message.getFrom());
                } catch (RoomState.ClientNotJoinedException e) {
                    final Message error = message.createError(new StanzaError(StanzaError.Type.AUTH, Condition.FORBIDDEN, "You are not a participant of this room"));
                    externalComponent.sendMessage(error);
                    return;
                }
                Message echo = new Message();
                echo.setType(Message.Type.GROUPCHAT);
                echo.setFrom(roomJid.withResource(sender.getNick()));
                echo.setId(message.getId());
                echo.setBody(message.getBody());
                echo.addExtensions(message.getExtensions());
                for (Participant participant : roomState.getParticipants()) {
                    for (Jid client : participant.getJoinedClients()) {
                        echo.setTo(client);
                        externalComponent.sendMessage(echo);
                    }
                }
            }
        });

        ServiceDiscoveryManager serviceDiscoveryManager = externalComponent.getManager(ServiceDiscoveryManager.class);
        serviceDiscoveryManager.addIdentity(Identity.conferenceText());
        serviceDiscoveryManager.addFeature(Muc.NAMESPACE);

        externalComponent.getManager(EntityCapabilitiesManager.class).setEnabled(false);
        externalComponent.getManager(PresenceManager.class).setEnabled(false);

        externalComponent.addInboundPresenceListener(presenceEvent -> {
            final Presence presence = presenceEvent.getPresence();
            Muc muc = presence.getExtension(Muc.class);
            Jid roomJid = presence.getTo().asBareJid();
            String desiredNick = presence.getTo().getResource();
            Jid client = presence.getFrom();
            if (roomJid.getLocal() == null) {
                System.out.println("presence to service received");
                return;
            }
            RoomState roomState = ROOMS.computeIfAbsent(roomJid, r -> new RoomState());
            if (muc != null && presence.getType() == null) {
                System.out.println(client + " joins room " + roomJid + " as " + desiredNick);
                try {
                    final String nick = roomState.join(client, desiredNick);
                    Presence selfPresence = new Presence(client);
                    selfPresence.setFrom(roomJid.withResource(nick));
                    selfPresence.addExtension(MucUser.withItem(Affiliation.NONE, Role.PARTICIPANT, Jid.of(client.asBareJid()), Status.SELF_PRESENCE, Status.SERVICE_HAS_ASSIGNED_OR_MODIFIED_NICK));

                    for (Participant participant : roomState.getParticipants()) {
                        if (participant.getJid().equals(client.asBareJid())) {
                            continue;
                        }
                        Presence participantPresence = new Presence(client);
                        participantPresence.setFrom(roomJid.withResource(participant.getNick()));
                        participantPresence.addExtension(MucUser.withItem(Affiliation.NONE, Role.PARTICIPANT, Jid.of(participant.getJid())));
                        externalComponent.sendPresence(participantPresence);
                        for (Jid joinedClient : participant.getJoinedClients()) {
                            Presence newUserPresence = new Presence(joinedClient);
                            newUserPresence.setFrom(roomJid.withResource(nick));
                            newUserPresence.addExtension(MucUser.withItem(Affiliation.NONE, Role.PARTICIPANT, Jid.of(client.asBareJid())));
                            externalComponent.sendPresence(newUserPresence);
                        }
                    }

                    externalComponent.sendPresence(selfPresence);
                } catch (RoomState.NickAlreadyInUseException e) {
                    Presence errorPresence = presence.createError(Condition.CONFLICT);
                    externalComponent.sendPresence(errorPresence);
                }
            }
            if (presence.getType() == Presence.Type.UNAVAILABLE) {
                System.out.println(client + " leaves room " + roomJid);
                if (roomState.leave(client, desiredNick)) {
                    for (Participant participant : roomState.getParticipants()) {
                        for (Jid joinedClient : participant.getJoinedClients()) {
                            Presence leaveNotificationPresence = new Presence(joinedClient);
                            leaveNotificationPresence.setType(Presence.Type.UNAVAILABLE);
                            leaveNotificationPresence.setFrom(roomJid.withResource(desiredNick));
                            leaveNotificationPresence.addExtension(MucUser.withItem(Affiliation.NONE, Role.NONE, Jid.of(client.asBareJid())));
                            externalComponent.sendPresence(leaveNotificationPresence);
                        }
                    }
                }
                Presence selfPresence = new Presence(client);
                selfPresence.setType(Presence.Type.UNAVAILABLE);
                selfPresence.setFrom(roomJid.withResource(desiredNick));
                selfPresence.addExtension(MucUser.withItem(Affiliation.NONE, Role.PARTICIPANT, Jid.of(client.asBareJid()), Status.SELF_PRESENCE));
            }
        });

        connectAndKeepRetrying(externalComponent);
    }

    private static void connectAndKeepRetrying(final ExternalComponent component) {
        while (true) {
            try {
                component.connect();
                while (component.isConnected()) {
                	System.out.println("connected");
                    sleep(500);
                }
            } catch (XmppException e) {
                System.err.println(e.getMessage());
            }
            sleep(5000);
        }
    }

    private static void sleep(long interval) {
        try {
            Thread.sleep(interval);
        } catch (InterruptedException e) {

        }
    }


}

**Comment by mkassir95** [comment]
This is my ejabberd.yml

> 
hosts:
  - localhost

loglevel: info


  
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    #starttls: true
    #certfile: "./xmpp_example_com.pem"
    

  -
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      /admin: ejabberd_web_admin
      /.well-known/acme-challenge: ejabberd_acme
  
  -
    port: 5281
    module: ejabberd_http
    ip: "::"
    request_handlers:
      /api: mod_http_api
      /oauth: ejabberd_oauth
  
  -
    port: 5347
    ip: "::"
    module: ejabberd_service
    hosts:
      "mymuc.domain.tld":
        password: "mysecret"
     
acl:
 exampleorg:
   server: localhost
    
api_permissions:
  "admin api permsions":
    from:
      - ejabberd_ctl
      - mod_http_api
    who:
      acl: exampleorg
    what: "*"
    




    
modules:
  mod_admin_extra: {}
  mod_muc:
    access:
      - allow
    access_admin:
      - allow: admin
    access_create: muc_create
    access_persistent: muc_create
    access_mam:
      - allow
    default_room_options:
      allow_subscription: true  # enable MucSub
      allow_private_messages: true
      allow_user_invites: true
      mam: true
      persistent: true
  mod_muc_admin: {}
  mod_push_keepalive: 
    wake_on_start: true
  mod_offline: {}
  mod_push: {}

**Comment by vitalyster** [comment]
Your component will receive messages to "mymuc.domain.tld", not to "mohammad@localhost"

**Comment by mkassir95** [comment]
Hello @vitalyster

you mean I should send the message to the component?

**Comment by mkassir95** [comment]
I am actually using this code https://github.com/xmpp-docs/simple-muc-component-java
 I just changed the domain name in addition to the configurations in the ejabberd.yml file

**Comment by mkassir95** [comment]
you mean I should send message to  mymuc.domain.tld, like the below picture ?(but also no logs in the console)
![image](https://user-images.githubusercontent.com/72728047/209678555-d4290618-f9bc-4895-a1f5-9e6d58b9f85d.png)

**Comment by mkassir95** [comment]
Thank I figured it out
![image](https://user-images.githubusercontent.com/72728047/209688999-f3e649f8-99c1-40a5-88b3-63a76387e9b1.png)

**Comment by mkassir95** [comment]
But  what is there a method to send the message to user@localhost and the message is forwarded to te component?

**Comment by vitalyster** [comment]
You can handle messages for all users of the **component** like `user@mymuc.domain.tld`. Additionally you can configure top-level `localhost` domain to be handled by component but this may require additional setup on server side.

**Comment by mkassir95** [comment]
thank you very mush

**Comment by mkassir95** [comment]
I just have a last question, in this case I have to send two request one to `localhost` and other to ` user@mymuc.domain.tld` so what is the benifet?

**Comment by vitalyster** [comment]
I think you misunderstand something. `localhost` and `user@mymuc.domain.tld` are two totally different addresses. You should understand who should receive your request, not needed to send requests to multiple random addresses

**Comment by mkassir95** [comment]
ok I understood, but in this case I need to register  the users  to `user@mymuc.domain.tld` , but this can not be done this 'user@mymuc.domain.tld' is not a virtual host

**Comment by vitalyster** [comment]
If your external component have `mymuc.domain.tld` address then all messages to users of this component (`user1@mymuc.domain.tld`, `user2@mymuc.domain.tld`, etc.) will be delivered to component. It is the component task to handle users and route their messages.
What you are trying to do? You want to write MUC component? That will be too complex task.

**Comment by mkassir95** [comment]
I actually need to handle offline messages. I want to send a notification to users who are offline. I am thinking of checking first if the receiver is offline (by presence API), if it is offline then I send the message to the component where there I can some logic to push notification to his phone

**Comment by vitalyster** [comment]
It is not the task of external component, it can handle own users only, not users from other "virtual host". That kind of plugin you needed can be written using some internal server plugin API only, not the XMPP component one.

**Comment by mkassir95** [comment]
ok I understood, thank you very much for your patience
